[package]
name = "burau4_mod_p"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "0.14.3"
num = "0.4.1"
rand = "0.8.5"
rand_pcg = "0.3.1"
rayon = "1.9.0"
rng = "0.1.0"
